This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./LRS.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file LRS.acn....done (116 entries accepted, 0 rejected).
Sorting entries....done (901 comparisons).
Generating output file LRS.acr....done (57 lines written, 0 warnings).
Output written in LRS.acr.
Transcript written in LRS.alg.
